config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#sign_up'
  post '/signup', to: 'users#sign_up_process'

  scope 'admin' do
    resources :users do
      member do
        get :tasks
      end
    end
  end

  resources :tasks do
    collection do
      get :list
      post :sort
    end
    member do
      get :show_user_task
    end
  end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, counter_cache: true
  has_one :sort_list, dependent: :destroy
  has_many :task_tags, dependent: :destroy
  has_many :tags, through: :task_tags

  validates :title, :content, presence: { message: I18n.t('must_be_presence') }
  validates :priority, :status, presence: true
  validates :start_at, presence: { message: I18n.t('must_be_choose_date') }
  validates :deadline_at, presence: { message: I18n.t('must_be_choose_date') }
  validate :start_at_cannot_greater_than_deadline

  enum status: { pending: 0, processing: 1, completed: 2 }
  enum priority: { primary: 0, secondly: 1, common: 2 }

  private
  def start_at_cannot_greater_than_deadline
    return if start_at.nil? || deadline_at.nil?
    if start_at > deadline_at
      errors.add(:start_at, I18n.t('start_at_cannot_greater_than_deadline'))
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :task_find, only: [:edit, :show, :show_user_task, :update, :destroy]
  before_action :reorder, only: [:index, :list]
  before_action :current, only: [:show, :show_user_task, :edit]

  def index
    @q = current_user.tasks.includes(:tags, :sort_list).order('sort_lists.sort asc').ransack(params[:q])
    @tags = Tag.all
    @tasks = @q.result.page(params[:page]).per(10)
  end

  def show
  end

  def show_user_task
  end

  def new
    @task = current_user.tasks.new
    @tags = Tag.all
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      @task.create_sort_list(sort: 0)
      if tag_params
        tag_params.each do |tag_id|
          @task.task_tags.create(tag_id: tag_id)
        end
      end
      redirect_to root_path, notice: t('create_success')
    else
      task_save_error
      render :new
    end
  end

  def edit
    @checked_tags = @task.tags
    @tags = Tag.all - @checked_tags
  end

  def update
    if @task.update(task_params)
      if tag_params
        unchecked = @task.tags.ids - tag_params
        unchecked.each do |tag_id|
          @task.task_tags.find_by(tag_id: tag_id).delete
        end
        checked = tag_params - @task.tags.ids
        checked.each do |tag_id|
          @task.task_tags.create(tag_id: tag_id)
        end
      end
      redirect_to root_path, notice: t('edit_success')
    else
      task_save_error
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path, notice: t('delete_success')
  end

  def list
    @tasks = current_user.tasks.includes(:sort_list).order('sort_lists.sort asc')
  end

  def sort
    lists = sort_params
    lists.each_with_index do |list, index|
      item = Task.find(list).sort_list.update(sort: index)
    end
    redirect_to list_tasks_path, notice: t('edit_success')
  end

  private

  def current
    @current_user = current_user
  end

  def task_params
    params.require(:task).permit(:title, :content, :priority, :status, :start_at, :deadline_at)
  end

  def tag_params
    if params[:tag_ids]
      return params.require(:tag_ids)
    else
      return []
    end
  end

  def task_save_error
    @errors = @task.errors.messages
    @checked_tags = tag_params.map do |tag_id|
      Tag.find(tag_id)
    end
    @tags = Tag.all - @checked_tags
  end

  def task_find
    @task = Task.find(params[:id])
  end

  def sort_params
    params[:lists]
  end

  def reorder
    lists = current_user.tasks.includes(:sort_list).order('sort_lists.sort asc').ids
    lists.each_with_index do |list, index|
      item = Task.find(list).sort_list.update(sort: index)
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def task_error_message(item)
    if @errors.present?
      if @errors[item.to_sym].present?
        '* ' + @errors[item.to_sym].join(',')
      end
    end
  end

  def task_author?(task)
    task.id == current.user
  end
end

app/views/tasks/_form.html.erb
<%= form_with model: task, url: path, method: method, errors: errors, local: true, class: 'form_task' do |f| %>
  <%= f.text_field :title, placeholder: 'Title', class: 'w-100 mt-3 px-2' %>
  <span class='d-block mt-1 pl-2 text-danger'><%= task_error_message('title') %></span>

  <%= f.text_area :content, placeholder: 'Content', class: 'w-100 mt-3 px-2 content' %>
  <span class='d-block mt-1 pl-2 text-danger'><%= task_error_message('content') %></span>

  <div class='w-100 mt-3'>
    <%= f.label :priority, Task.human_attribute_name('priority'), class: 'mr-2'%>
    <%= f.radio_button :priority, 'primary' %>
    <%= f.label :priority_primary, Task.human_attribute_name('primary') %>
    <%= f.radio_button :priority, 'secondly' %>
    <%= f.label :priority_secondly, Task.human_attribute_name('secondly') %>
    <%= f.radio_button :priority, 'common', checked: true %>
    <%= f.label :priority_common, Task.human_attribute_name('common') %>
  </div>

  <div class='w-100 mt-3'>
    <%= f.label :status, Task.human_attribute_name('status'), class: 'mr-2' %>
    <%= f.radio_button :status, 'pending', checked: true %>
    <%= f.label :status_pending, Task.human_attribute_name('pending') %>
    <%= f.radio_button :status, 'processing' %>
    <%= f.label :status_processing, Task.human_attribute_name('processing') %>
    <%= f.radio_button :status, 'completed' %>
    <%= f.label :status_completed, Task.human_attribute_name('completed') %>
  </div>

  <div class='w-100 mt-3'>
    <%= f.label :start_at, Task.human_attribute_name('start_at'), class: 'mr-2' %>
    <%= f.date_field :start_at, value: DateTime.now.to_s(:taskdate), class: 'px-2' %>
  </div>
  <span class='d-block mt-1 pl-2 text-danger'><%= task_error_message('start_at') %></span>

  <div class='w-100 mt-3'>
    <%= f.label :deadline_at, Task.human_attribute_name('deadline_at'), class: 'mr-2' %>
    <%= f.date_field :deadline_at, value: DateTime.now.to_s(:taskdate), class: 'px-2' %>
  </div>
  <span class='d-block mt-1 pl-2 text-danger'><%= task_error_message('deadline_at') %></span>

  <div class='w-100 mt-3 d-flex flex-wrap'>
    <% if checked_tags %>
      <% checked_tags.each do |tag| %>
        <div class='tag d-flex align-item-center rounded border border-1 border-dark mr-2 mt-2'>
          <%= check_box_tag "tag_ids[]", tag.id, false, id: "label_#{tag.label}", checked: true %>
          <%= label_tag "label[#{tag.label}]", tag.label, class: 'px-2 py-1 mb-0' %>
        </div>
      <% end %>
    <% end %>
    <% tags.each do |tag| %>
    <div class='tag d-flex align-item-center rounded border border-1 border-dark mr-2 mt-2'>
      <%= check_box_tag "tag_ids[]", tag.id, false, id: "label_#{tag.label}" %>
      <%= label_tag "label[#{tag.label}]", tag.label, class: 'px-2 py-1 mb-0' %>
    </div>
    <% end %>
  </div>

  <div class='button mt-3 mb-5 d-flex justify-content-end'>
    <%= link_to t('cancel'), tasks_path, class: 'border-bottom border-secondary shadow btn btn-md btn-default px-3 py-2 mr-3' %>
    <%= f.submit t('submit'), class: 'border-bottom shadow btn btn-md btn-primary px-3 py-2' %>
  </div>
<% end %>

app/views/tasks/_search.html.erb
<%= search_form_for q do |f| %>
<div class='search border border-1 border-dark px-2 py-2 mt-3'>
<h4 class='mb-0'><%= t('search') %></h4>
  <div class='w-100 d-flex flex-wrap'>
    <% @tags.each do |tag| %>
    <div class='tag d-flex align-item-center rounded border border-1 border-dark mr-2 mt-2'>
      <%= f.radio_button :tags_id_eq, tag.id %>
      <%= f.label "tags_id_eq_#{tag.id}", tag.label, class: 'px-2 py-1 mb-0' %>
    </div>
    <% end %>
  </div>
  <div class='d-flex align-item-center mt-4'>
    <%= f.select :status_eq, options_for_select([[Task.human_attribute_name('pending'), '0'], [Task.human_attribute_name('processing'), '1'], [Task.human_attribute_name('completed'), '2']]), include_blank: t('choose_status') %>
    <%= f.search_field :title_cont, placeholder: 'Search', value:'', class: 'ml-2 w-50' %>
    <%= link_to t('reset'), tasks_path, class: 'btn btn-light text-dark border-secondary ml-auto mr-2' %>
    <%= f.submit t('search'), class: 'btn btn-dark text-light border-secondary ml-2 mr-2' %>
  </div>
</div>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'shared/topbar' %>
<section class="container-fluid">
<h2 class='mt-3'><%= t('edit_task') %></h2>
<%= render 'form', task: @task, tags: @tags, path: task_path, errors: @errors, method: 'PATCH', checked_tags: @checked_tags %>
</section>

app/views/tasks/index.html.erb
<%= render 'shared/topbar' %>
<section class="container-fluid">
  <h2 class='mt-3'><%= t('TaskLists') %></h2>
  <%= render 'search', q: @q %>
  <%= content_tag :table, class: 'table mt-3' do %>
    <thead>
      <tr>
        <%= content_tag :th, sort_link(@q, 'sort_list_sort', 'No') %>
        <%= content_tag :th, sort_link(@q, 'priority', Task.human_attribute_name('priority')) %>
        <%= content_tag :th, sort_link(@q, 'created_at', Task.human_attribute_name('created_at')) %>
        <th><%= Task.human_attribute_name('title') %></th>
        <th><%= Task.human_attribute_name('content') %></th>
        <th><%= TaskTag.human_attribute_name('label') %></th>
        <%= content_tag :th, sort_link(@q, 'start_at', Task.human_attribute_name('start_at')) %>
        <%= content_tag :th, sort_link(@q, 'deadline_at', Task.human_attribute_name('deadline_at')) %>
        <th colspan='2'><%= Task.human_attribute_name('status') %></th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
      <tr class='list'>
        <td class='index'><%= task.sort_list.sort + 1 %></td>
        <td class='priority'><%= Task.human_attribute_name(task.priority) %></td>
        <td class='created_at'><%= task.created_at.to_s(:taskdate) %></td>
        <td class='title'><%= link_to task_path(task.id) do %><%= truncate(task.title, length: 20) %><% end %></td>
        <td class='content'><%= link_to task_path(task.id) do %><%= truncate(task.content, length: 20) %><% end %></td>
        <td class='tags'>
          <div class='d-flex flex-wrap'>
          <% if task.tags.present? %>
            <% task.tags.each do |tag| %>
              <span class='tag rounded border border-1 border-dark px-1 py-1 mr-1 mb-1'><%= tag.label %></span>
            <% end %>
          <% end %>
          </div>
        </td>
        <td class='start_at'><%= task.start_at.to_s(:taskdate) %></td>
        <td class='deadline_at'><%= task.deadline_at.to_s(:taskdate) %></td>
        <td class='status'><%= Task.human_attribute_name(task.status) %></td>
        <td>
          <%= link_to t('edit'), edit_task_path(task), class: 'border-bottom shadow btn btn-md btn-primary px-1 py-1 mr-1' %>
          <%= link_to t('delete'), task_path(task), method:'DELETE', class: 'border-bottom shadow btn btn-md btn-danger px-1 py-1', data: { confirm: t('confirm_delete') } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  <% end %>
</section>
<%= paginate @tasks %>

app/views/tasks/list.html.erb
<%= render 'shared/topbar' %>
<section class="container-fluid">
  <h2 class='mt-3 d-inline-block'><%= t('custom_sort') %></h2>
  <p class='d-inline-block mt-3 ml-3'><%= t('setting_sort') %></p>
  <%= form_with url: sort_tasks_path do %>
  <div class='button d-flex justify-content-end'>
    <%= link_to t('cancel'), list_tasks_path, class: 'border border-bottom btn btn-light mx-2' %>
    <%= submit_tag t('submit'), method: 'post', class: 'border border-bottom btn btn-primary ml-2 mr-3' %>
  </div>
  <table class='table mt-3'>
    <thead>
      <tr>
        <th>No</th>
        <th><%= Task.human_attribute_name('priority') %></th>
        <th><%= Task.human_attribute_name('created_at') %></th>
        <th><%= Task.human_attribute_name('title') %></th>
        <th><%= Task.human_attribute_name('content') %></th>
        <th><%= TaskTag.human_attribute_name('label') %></th>
        <th><%= Task.human_attribute_name('start_at') %></th>
        <th><%= Task.human_attribute_name('deadline_at') %></th>
        <th><%= Task.human_attribute_name('status') %></th>
      </tr>
    </thead>
    <tbody id='lists'>
      <% @tasks.each do |task| %>
      <tr class='list' draggable='true'>
        <td><%= hidden_field_tag "lists[]", task.id, size: 5, id: false %><%= task.sort_list.sort + 1 %></td>
        <td class='priority'><%= Task.human_attribute_name(task.priority) %></td>
        <td class='created_at'><%= task.created_at.to_s(:taskdate) %></td>
        <td class='title'><%= truncate(task.title, length:30) %></td>
        <td class='content'><%= truncate(task.content, length:20) %></td>
        <td class='tags'>
          <div class='d-flex flex-wrap'>
          <% if !task.tags.nil? %>
            <% task.tags.each do |tag| %>
              <span class='tag rounded border border-1 border-dark px-1 py-1 mr-1 mb-1'><%= tag.label %></span>
            <% end %>
          <% end %>
          </div>
        </td>
        <td class='start_at'><%= task.start_at.to_s(:taskdate) %></td>
        <td class='deadline_at'><%= task.deadline_at.to_s(:taskdate) %></td>
        <td class='status'><%= Task.human_attribute_name(task.status) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
</section>
<%= javascript_pack_tag 'application' %>

app/views/tasks/new.html.erb
<%= render 'shared/topbar' %>
<section class="container-fluid">
  <h2 class='mt-3'><%= t('new_task') %></h2>
<%= render 'form', task: @task, tags: @tags, path: tasks_path, errors: @errors, method: 'POST', checked_tags: @checked_tags %>
</section>

app/views/tasks/show.html.erb
<%= render 'shared/topbar' %>
<section class="container-fluid">
<h2 class='mt-3'><%= t('TaskDetail') %></h2>
<table class='table'>
  <%= render 'shared/taskshow', task: @task %>
  <tfoot>
    <tr>
      <td colspan='2'>
        <div class='button mt-3 mb-5 d-flex justify-content-end'>
          <%= link_to t('TaskLists'), tasks_path, class: 'border-bottom border-secondary shadow btn btn-md btn-default px-3 py-2 mr-auto' %>
          <%= link_to t('edit'), edit_task_path(@task), class: 'border-bottom shadow btn btn-md btn-primary px-3 py-2 mr-4' %>
          <%= link_to t('delete'), task_path(@task), method:'DELETE', class: 'border-bottom shadow btn btn-md btn-danger px-3 py-2', data: { confirm: t('confirm_delete') } %>
        </div>
      </td>
    </tr>
  </tfoot>
</table>
</section>

app/views/tasks/show_user_task.html.erb
<%= render 'shared/topbar' %>
<section class="container-fluid">
<h2 class='mt-3'><%= t('TaskDetail') %>( <%= @task.user.username %> )</h2>
<table class='table'>
  <%= render 'shared/taskshow', task: @task %>
  <tfoot>
    <tr>
      <td colspan='2'>
        <div class='button mt-3 mb-5 d-flex justify-content-end'>
          <%= link_to t('back'), tasks_user_path(@task.user_id), class: 'border-bottom border-secondary shadow btn btn-md btn-default px-3 py-2 mr-auto' %>
        </div>
      </td>
    </tr>
  </tfoot>
</table>
</section>

app/views/tasks/sort.html.erb
<%= render 'topbar' %>
<section class="container-fluid">
  <h2 class='mt-3'><%= t('TaskLists') %></h2>
  <p><%= t('setting_sort') %></p>
  <table class='table mt-3'>
    <thead>
      <tr>
        <th><%= Task.human_attribute_name('priority') %></th>
        <th><%= Task.human_attribute_name('created_at') %></th>
        <th><%= Task.human_attribute_name('title') %></th>
        <th><%= Task.human_attribute_name('content') %></th>
        <th><%= TaskTag.human_attribute_name('label') %></th>
        <th><%= Task.human_attribute_name('start_at') %></th>
        <th><%= Task.human_attribute_name('deadline_at') %></th>
        <th><%= Task.human_attribute_name('status') %></th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
      <tr class='list'>
        <td class='priority'><%= Task.human_attribute_name(task.priority) %></td>
        <td class='created_at'><%= task.created_at.to_s(:taskdate) %></td>
        <td class='title'><%= truncate(task.title) %></td>
        <td class='content'><%= truncate(task.content) %></td>
        <td class='tags'>
          <% if !task.tags.nil? %>
            <% task.tags.each do |tag| %>
              <span class='tag'><%= tag.label %></span>
            <% end %>
          <% end %>
        </td>
        <td class='start_at'><%= task.start_at.to_s(:taskdate) %></td>
        <td class='deadline_at'><%= task.deadline_at.to_s(:taskdate) %></td>
        <td class='status'><%= Task.human_attribute_name(task.status) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>
<%= javascript_pack_tag 'application' %>