config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#sign_up'
  post '/signup', to: 'users#sign_up_process'

  scope 'admin' do
    resources :users do
      member do
        get :tasks
      end
    end
  end

  resources :tasks do
    collection do
      get :list
      post :sort
    end
    member do
      get :show_user_task
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  before_create :digest_password
  before_destroy :vaild_admin_account

  has_many :tasks, dependent: :destroy

  validates :username, presence: { message: I18n.t('must_be_presence') }
  validates :email, on: :create, presence: { message: I18n.t('must_be_presence') }
  validates :email, on: :create, uniqueness: { message: I18n.t('the_email_has_already_been_used')}

  validates :password, on: :create, presence: { message: I18n.t('must_be_presence') }
  validates :password, on: :create, length: { minimum: 6, too_short: I18n.t('more_than_6_character') }
  validates :password_confirmation, on: :create, presence: { message: I18n.t('must_be_presence') }
  validates :password, confirmation: true, on: :create


  enum role: { member: 0, admin: 1 }

  private
  def digest_password
    self.password = Digest::SHA256.hexdigest password
  end

  def vaild_admin_account
    if admin?
      if User.admin.count <= 1
        throw :abort
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:sign_up, :sign_up_process]
  before_action :permission_check!, except: [:sign_up, :sign_up_process]
  before_action :user_find, only: [:edit, :show, :tasks, :update, :destroy]

  def index
    @users = User.page(params[:page]).per(10)
  end

  def tasks
    @tasks = @user.tasks.includes(:tags).page(params[:page]).per(10)
  end

  def show
  end

  def new
    @user = User.new
  end

  def sign_up
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: t('create_success')
    else
      render :new
    end
  end

  def sign_up_process
    @user = User.new(user_params)

    if @user.save
      log_in @user
      redirect_to tasks_path, notice: t('welcome')
    else
      render :sign_up
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: t('edit_success')
    else
      render :edit
    end
  end

  def destroy
    if @user.id == current_user.id
      redirect_to users_path, notice: t('you_can_not_delete_yourself')
    else
      if @user.destroy
        redirect_to users_path, notice: t('delete_success')
      else
        redirect_to users_path, notice: t('admin_less_than_1')
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :role)
  end

  def user_find
    @user = User.find(params[:id])
  end

  def pwd_digest(pwd)
    Digest::SHA256.hexdigest pwd
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def error_message(item)
    if @user.errors.any?
      if @user.errors.messages[item.to_sym].present?
        '* ' + @user.errors.messages[item.to_sym].join(',')
      end
    end
  end
end

app/views/users/_form.html.erb
<% if @current_user.admin? %>
  <h2 class='mt-3'><%= t('new_user') %></h2>
<% else %>
  <h2 class='mt-3 text-primary'><%= t('signup') %></h2>
<% end %>
<%= form_with model: user, url: path, method: 'POST', local: true, class:'form_user' do |f| %>
  <%= f.text_field :username, placeholder: 'User Name', class: 'w-100 mt-3 px-2' %>
  <span class='d-block mt-1 pl-2 text-danger'><%= error_message('username') %></span>
  <%= f.email_field :email, placeholder: 'E-mail', class: 'w-100 mt-3 px-2' %>
  <span class='d-block mt-1 pl-2 text-danger'><%= error_message('email') %></span>
  <%= f.password_field :password, placeholder: 'Password', type: 'password', class: 'w-100 mt-3 px-2' %>
  <span class='d-block mt-1 pl-2 text-danger'><%= error_message('password') %></span>
  <%= f.password_field :password_confirmation, placeholder: 'Password Confirmation', type: 'password', class: 'w-100 mt-3 px-2' %>
  <span class='d-block mt-1 pl-2 text-danger'><%= error_message('password_confirmation') %></span>
  <% if @current_user.admin? %>
    <%= label_tag t('role'), false, class: 'pr-2 py-2 mt-3' %>
    <%= f.radio_button :role, 'admin' %>
    <%= f.label :role_admin, User.human_attribute_name('admin'), class: 'pl-1 pr-3 py-2 mt-3' %>
    <%= f.radio_button :role, 'member' %>
    <%= f.label :role_member, User.human_attribute_name('member'), class: 'pl-1 pr-3 py-2 mt-3' %>
  <% end %>
  <div class='button mt-4 d-flex justify-content-end'>
    <% if @current_user.admin? %>
      <%= link_to t('cancel'), users_path, class: 'shadow btn btn-md btn-default px-3 py-2 mr-3' %>
    <% else %>
      <%= link_to t('back_signin'), users_path, class: 'shadow btn btn-md btn-default px-3 py-2 mr-auto' %>
    <% end %>
    <%= f.submit t('submit'), class: 'shadow btn btn-md btn-primary px-3 py-2' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'shared/topbar' %>
<section class="container-fluid">
  <h2 class='mt-3'><%= t('edit_user') %></h2>

<%= form_with model: @user, url: user_path, method: 'PATCH', local: true, class:'form_user' do |f| %>
  <%= label_tag t('user_name'), false, class: 'px-2 mt-3' %>
  <%= f.text_field :username, placeholder: 'User Name', class: 'w-100 px-2' %>
  <span class='d-block mt-1 pl-2 text-danger'><%= error_message('username') %>
 </span>
  <%= label_tag t('role'), false, class: 'px-2 py-2 mt-3' %>
  <%= f.radio_button :role, 'admin' %>
  <%= f.label :role_admin, User.human_attribute_name('admin'), class: 'pl-1 pr-3 py-2 mt-3' %>
  <%= f.radio_button :role, 'member' %>
  <%= f.label :role_member, User.human_attribute_name('member'), class: 'pl-1 pr-3 py-2 mt-3' %>
  <div class='button mt-3 d-flex justify-content-end'>
    <%= link_to t('cancel'), users_path, class: 'border-bottom border-secondary shadow btn btn-md btn-default px-3 py-2 mr-3' %>
    <%= f.submit t('submit'), class: 'border-bottom shadow btn btn-md btn-primary px-3 py-2' %>
  </div>
<% end %>
</section>

app/views/users/index.html.erb
<%= render 'shared/topbar' %>
<section class="container-fluid">
<h2 class='mt-3'><%= t('UserLists') %></h2>
<table class='table mt-3'>
  <thead>
    <tr>
      <th><%= t('user_name') %></th>
      <th><%= t('email') %></th>
      <th><%= t('task_count') %></th>
      <th><%= t('role') %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>
        <%= link_to user_path(user.id) do %>
          <%= user.username %>
        <% end %>
      </td>
      <td>
        <%= link_to user_path(user.id) do %>
        <%= user.email %>
        <% end %>
      </td>
      <td>
        <%= link_to tasks_user_path(user.id) do %>
          <%= user.tasks_count %>
        <% end %>
      </td>
      <td><%= User.human_attribute_name(user.role) %></td>
      <td>
        <%= link_to t('edit'), edit_user_path(user), class: 'border-bottom shadow btn btn-md btn-primary px-1 py-1 mr-1' %>
        <%= link_to t('delete'), user_path(user), method:'DELETE', class: 'border-bottom shadow btn btn-md btn-danger px-1 py-1', data: { confirm: t('confirm_delete') } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</section>
<%= paginate @users %>

app/views/users/new.html.erb
<%= render 'shared/topbar' %>
<section class="container-fluid">
<%= render 'form', user: @user, path: users_path %>
</section>

app/views/users/show.html.erb
<%= render 'shared/topbar' %>
<section class="container-fluid">
  <h2 class='mt-3'><%= t('UserDetail') %>( <%= @user.username %> )</h2>
  <%= content_tag :table , class: 'table mt-3' do %>
    <tr>
      <th><%= I18n.t('role') %></th>
      <td><%= @user.role %></td>
    </tr>
      <th><%= I18n.t('email') %></th>
      <td><%= @user.email %></td>
    <tr>
      <th><%= User.human_attribute_name('created_at') %></th>
      <td><%= @user.created_at %></td>
    </tr>
    <tr>
      <th><%= I18n.t('task_count') %></th>
      <td>
        <%= link_to tasks_user_path(@user.id) do %>
          <%= @user.tasks_count %></td>
        <% end %>
    </tr>
    <tr>
      <td colspan='2'>
        <div class='button mt-3 mb-5 d-flex justify-content-end'>
        <%= link_to t('UserLists'), users_path, class: 'border-bottom border-secondary shadow btn btn-md btn-default px-3 py-2 mr-auto' %>
        <%= link_to t('edit'), edit_user_path(@user), class: 'border-bottom shadow btn btn-md btn-primary px-3 py-2 mr-4' %>
        <%= link_to t('delete'), user_path(@user), method:'DELETE', class: 'border-bottom shadow btn btn-md btn-danger px-3 py-2', data: { confirm: t('confirm_delete') } %>
      </td>
    </tr>
  <% end %>
</section>

app/views/users/sign_up.html.erb
<section class="container-fluid">
<div class='form_signin rounded shadow mt-5 mx-auto px-4 pt-2 pb-4'>
  <%= render 'form', user: @user, path: signup_path %>
</div>
</section>

app/views/users/tasks.html.erb
<%= render 'shared/topbar' %>
<section class="container-fluid">
  <h2 class='mt-3'><%= t('TaskLists') %>( <%= @user.username %> )</h2>
  <%= content_tag :table , class: 'table mt-3' do %>
    <thead>
      <tr>
        <th><%= Task.human_attribute_name('priority') %></th>
        <th><%= Task.human_attribute_name('created_at') %></th>
        <th><%= Task.human_attribute_name('title') %></th>
        <th><%= Task.human_attribute_name('content') %></th>
        <th><%= TaskTag.human_attribute_name('label') %></th>
        <th><%= Task.human_attribute_name('start_at') %></th>
        <th><%= Task.human_attribute_name('deadline_at') %></th>
        <th><%= Task.human_attribute_name('status') %></th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
      <tr class='list'>
        <td class='priority'><%= Task.human_attribute_name(task.priority) %></td>
        <td class='created_at'><%= task.created_at.to_s(:taskdate) %></td>
        <td class='title'>
          <%= link_to show_user_task_task_path(task.id) do %>
            <%= truncate(task.title, length: 20) %>
          <% end %>
        </td>
        <td class='content'>
          <%= link_to show_user_task_task_path(task.id) do %>
            <%= truncate(task.content) %>
          <% end %>
        </td>
        <td class='tags'>
          <div class='d-flex flex-wrap'>
          <% if !task.tags.nil? %>
            <% task.tags.each do |tag| %>
              <span class='tag rounded border border-1 border-dark px-1 py-1 mr-1 mb-1'><%= tag.label %></span>
            <% end %>
          <% end %>
          </div>
        </td>
        <td class='start_at'><%= task.start_at.to_s(:taskdate) %></td>
        <td class='deadline_at'><%= task.deadline_at.to_s(:taskdate) %></td>
        <td class='status'><%= Task.human_attribute_name(task.status) %></td>
      </tr>
      <% end %>
    </tbody>
  <% end %>
</section>
<%= paginate @tasks %>