config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#sign_up'
  post '/signup', to: 'users#sign_up_process'

  scope 'admin' do
    resources :users do
      member do
        get :tasks
      end
    end
  end

  resources :tasks do
    collection do
      get :list
      post :sort
    end
    member do
      get :show_user_task
    end
  end

end

app/views/shared/_taskshow.html.erb
<tbody>
  <tr>
    <th><%= Task.human_attribute_name('title') %></th>
    <td><%= task.title %></td>
  </tr>
  <tr>
    <th><%= Task.human_attribute_name('content') %></th>
    <td><%= task.content %></td>
  </tr>
  <tr>
    <th><%= TaskTag.human_attribute_name('label') %></th>
    <td>
      <% task.tags.each do |tag| %>
        <span class='tag rounded border border-1 border-dark px-1 py-1'><%= tag.label %></span>
      <% end %>
    </td>
  </tr>
  <tr>
    <th><%= Task.human_attribute_name('start_at') %></th>
    <td><%= task.start_at.to_s(:taskdate) %></td>
  </tr>
  <tr>
    <th><%= Task.human_attribute_name('deadline_at') %></th>
    <td><%= task.deadline_at.to_s(:taskdate) %></td>
  </tr>
  <tr>
    <th><%= Task.human_attribute_name('status') %></th>
    <td><%= Task.human_attribute_name(task.status) %></td>
  </tr>
  <tr>
    <th><%= Task.human_attribute_name('priority') %></th>
    <td><%= Task.human_attribute_name(task.priority) %></td>
  </tr>
  <tr>
    <th><%= Task.human_attribute_name('created_at') %></th>
    <td><%= task.created_at.to_s(:taskdate) %></td>
  </tr>
</tbody>

app/views/shared/_topbar.html.erb
<div class='container-fluid'>
  <nav class='topbar d-flex'>
    <%= link_to t('new_task'), new_task_path, class: 'rounded-pill bg-dark text-light px-4 py-2 mr-2' %>
    <%= link_to t('TaskLists'), root_path, class: 'rounded-pill bg-dark text-light px-4 py-2 mr-2' %>
    <%= link_to t('custom_sort'), list_tasks_path, class: 'rounded-pill bg-dark text-light px-4 py-2 mr-2' %>

    <% if @current_user.admin? %>
      <%= link_to t('new_user'), new_user_path, class: 'rounded-pill bg-primary text-light px-4 py-2 mr-2' %>
      <%= link_to t('UserLists'), users_path, class: 'rounded-pill bg-primary text-light px-4 py-2' %>
    <% end %>
  </nav>
</div>